/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/official-announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Official Announcements
         * @description Checked monetary facts and dates; not an eligibility decision or a live portal status.
         */
        get: operations["official_announcements_api_official_announcements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Login */
        post: operations["demo_login_api_auth_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/max": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Max Login */
        post: operations["max_login_api_auth_max_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile */
        get: operations["profile_api_profile_get"];
        /** Save Profile */
        put: operations["save_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measures/{measure_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Measure Detail */
        get: operations["measure_detail_api_measures__measure_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matches */
        post: operations["matches_api_matches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_api_preparation_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_preparation_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preparation-plans/{plan_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Check Item */
        patch: operations["check_item_api_preparation_plans__plan_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/admin/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Versions */
        get: operations["admin_versions_api_admin_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/measures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** New Measure */
        post: operations["new_measure_api_admin_measures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/versions/{version_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Version */
        post: operations["clone_version_api_admin_versions__version_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Draft */
        put: operations["update_draft_api_admin_versions__version_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/versions/{version_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition */
        post: operations["transition_api_admin_versions__version_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/max/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_api_max_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnouncementSource */
        AnnouncementSource: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Document */
            document: string;
            /** Sha256 */
            sha256: string;
            /** Finance Page */
            finance_page: number;
            /** Dates Page */
            dates_page: number;
        };
        /** AnnouncementView */
        AnnouncementView: {
            /** Measure Id */
            measure_id: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "grant" | "subsidy";
            /** Audience */
            audience: string;
            round: components["schemas"]["RoundInput"];
            /** Funding Year */
            funding_year: number;
            /** Budget Rub */
            budget_rub: string;
            /** Recipient Limit Rub */
            recipient_limit_rub?: string | null;
            /**
             * Limit Status
             * @enum {string}
             */
            limit_status: "stated" | "not_set_in_announcement";
            /** Finance Note */
            finance_note: string;
            /** Legal Edition */
            legal_edition: string;
            source: components["schemas"]["AnnouncementSource"];
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Missing Evidence */
            missing_evidence: string[];
            /**
             * Verification Scope
             * @default announcement_facts_only
             * @constant
             */
            verification_scope: "announcement_facts_only";
            /**
             * Deadline Status
             * @enum {string}
             */
            deadline_status: "not_started_in_notice" | "within_notice_dates" | "ended_in_notice";
            /**
             * Acceptance Status
             * @default unconfirmed
             * @constant
             */
            acceptance_status: "unconfirmed";
        };
        /** AnnouncementsView */
        AnnouncementsView: {
            /** Release Id */
            release_id: string;
            /** Items */
            items: components["schemas"]["AnnouncementView"][];
        };
        /** BusinessProfile */
        "BusinessProfile-Input": {
            /** Registration Region */
            registration_region?: string | null;
            /** Activity Region */
            activity_region?: string | null;
            /** Legal Form */
            legal_form?: ("ip" | "company" | "cooperative" | "individual") | null;
            /** Is Kfh */
            is_kfh?: boolean | null;
            /** Tax Regime */
            tax_regime?: ("eshn" | "usn" | "npd" | "general") | null;
            /** Sector */
            sector?: ("crops" | "livestock" | "processing" | "mixed") | null;
            /** Goal */
            goal?: ("equipment" | "construction" | "working_capital" | "consultation") | null;
            /** Expense Stage */
            expense_stage?: ("planned" | "incurred") | null;
            /** Years Active */
            years_active?: number | null;
            /** Own Funds */
            own_funds?: number | string | null;
            /** Is Sme */
            is_sme?: boolean | null;
            /** Special Category */
            special_category?: boolean | null;
        };
        /** BusinessProfile */
        "BusinessProfile-Output": {
            /** Registration Region */
            registration_region?: string | null;
            /** Activity Region */
            activity_region?: string | null;
            /** Legal Form */
            legal_form?: ("ip" | "company" | "cooperative" | "individual") | null;
            /** Is Kfh */
            is_kfh?: boolean | null;
            /** Tax Regime */
            tax_regime?: ("eshn" | "usn" | "npd" | "general") | null;
            /** Sector */
            sector?: ("crops" | "livestock" | "processing" | "mixed") | null;
            /** Goal */
            goal?: ("equipment" | "construction" | "working_capital" | "consultation") | null;
            /** Expense Stage */
            expense_stage?: ("planned" | "incurred") | null;
            /** Years Active */
            years_active?: number | null;
            /** Own Funds */
            own_funds?: string | null;
            /** Is Sme */
            is_sme?: boolean | null;
            /** Special Category */
            special_category?: boolean | null;
        };
        /** CheckInput */
        CheckInput: {
            /** Revision */
            revision: number;
            /** Done */
            done: boolean;
        };
        /** CheckView */
        CheckView: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FAIL" | "UNKNOWN";
            /** Field */
            field: string | null;
            /** Source Ref */
            source_ref: string;
            /** Children */
            children: components["schemas"]["CheckView"][];
        };
        /** DemoInput */
        DemoInput: {
            /**
             * Persona
             * @default farmer
             * @enum {string}
             */
            persona: "farmer" | "editor" | "second";
        };
        /** Document */
        Document: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Hint */
            hint: string;
        };
        /** DraftInput */
        DraftInput: {
            /** Revision */
            revision: number;
            data: components["schemas"]["VersionData-Input"];
            /** Rounds */
            rounds?: components["schemas"]["RoundInput"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchView */
        MatchView: {
            measure: components["schemas"]["MeasureView"];
            /**
             * Status
             * @enum {string}
             */
            status: "PASS" | "FAIL" | "UNKNOWN";
            /** Checks */
            checks: components["schemas"]["CheckView"][];
        };
        /** MatchesView */
        MatchesView: {
            /** Evaluation Id */
            evaluation_id: string;
            /** Results */
            results: components["schemas"]["MatchView"][];
        };
        /** MaxInput */
        MaxInput: {
            /** Init Data */
            init_data: string;
        };
        /** MeasureView */
        MeasureView: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Category */
            category: string;
            /** Synthetic */
            synthetic: boolean;
            /** Version Id */
            version_id: string;
            /** Version */
            version: number;
            /** State */
            state: string;
            /** Revision */
            revision: number;
            data: components["schemas"]["VersionData-Output"];
            /** Rounds */
            rounds: components["schemas"]["RoundView"][];
        };
        /** NewMeasure */
        NewMeasure: {
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "grant" | "subsidy" | "consultation";
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            data: components["schemas"]["VersionData-Input"];
            /** Rounds */
            rounds?: components["schemas"]["RoundInput"][];
        };
        /** PlanDocument */
        PlanDocument: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Hint */
            hint: string;
            /** Done */
            done: boolean;
        };
        /** PlanInput */
        PlanInput: {
            /** Round Id */
            round_id: string;
        };
        /** PlanView */
        PlanView: {
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["PlanDocument"][];
            measure: components["schemas"]["MeasureView"];
            /** Round Id */
            round_id: string;
            /** Needs Review */
            needs_review: boolean;
            /** Current Version Id */
            current_version_id: string | null;
        };
        /** RevisionInput */
        RevisionInput: {
            /** Revision */
            revision: number;
        };
        /** RoundInput */
        RoundInput: {
            /** Code */
            code: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Timezone
             * @default Europe/Moscow
             */
            timezone: string;
            /**
             * State
             * @default announced
             * @enum {string}
             */
            state: "announced" | "suspended" | "cancelled" | "unknown";
            /**
             * Application Url
             * Format: uri
             */
            application_url: string;
            /** Channel */
            channel: string;
        };
        /** RoundView */
        RoundView: {
            /** Code */
            code: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Timezone
             * @default Europe/Moscow
             */
            timezone: string;
            /**
             * State
             * @default announced
             * @enum {string}
             */
            state: "announced" | "suspended" | "cancelled" | "unknown";
            /**
             * Application Url
             * Format: uri
             */
            application_url: string;
            /** Channel */
            channel: string;
            /** Id */
            id: string;
            /** Availability */
            availability: string;
        };
        /** Rule */
        "Rule-Input": {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Field */
            field?: string | null;
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "in" | "gte" | "lte" | "all" | "any" | "manual";
            /** Value */
            value?: string | number | boolean | string[] | null;
            /** Children */
            children?: components["schemas"]["Rule-Input"][];
            /** Source Ref */
            source_ref: string;
        };
        /** Rule */
        "Rule-Output": {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Field */
            field?: string | null;
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "in" | "gte" | "lte" | "all" | "any" | "manual";
            /** Value */
            value?: string | number | boolean | string[] | null;
            /** Children */
            children?: components["schemas"]["Rule-Output"][];
            /** Source Ref */
            source_ref: string;
        };
        /** SessionView */
        SessionView: {
            user: components["schemas"]["UserView"];
            /** Csrf */
            csrf: string;
        };
        /** Source */
        Source: {
            /** Title */
            title: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Reference */
            reference: string;
            /** Published On */
            published_on: string;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Demo */
            demo: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionData */
        "VersionData-Input": {
            /** Summary */
            summary: string;
            /** Benefit */
            benefit: string;
            /** Operator */
            operator: string;
            /** Obligations */
            obligations: string;
            /** Contact */
            contact: string;
            /** Rules */
            rules?: components["schemas"]["Rule-Input"][];
            /** Documents */
            documents?: components["schemas"]["Document"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Verified At */
            verified_at?: string | null;
            /**
             * Verification Status
             * @default unverified
             * @enum {string}
             */
            verification_status: "unverified" | "verified" | "conflict";
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
            /**
             * Legal Edition
             * @default
             */
            legal_edition: string;
            /** Research Checked At */
            research_checked_at?: string | null;
            /** Missing Evidence */
            missing_evidence?: string[];
            /**
             * Verification Notes
             * @default
             */
            verification_notes: string;
        };
        /** VersionData */
        "VersionData-Output": {
            /** Summary */
            summary: string;
            /** Benefit */
            benefit: string;
            /** Operator */
            operator: string;
            /** Obligations */
            obligations: string;
            /** Contact */
            contact: string;
            /** Rules */
            rules?: components["schemas"]["Rule-Output"][];
            /** Documents */
            documents?: components["schemas"]["Document"][];
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Verified At */
            verified_at?: string | null;
            /**
             * Verification Status
             * @default unverified
             * @enum {string}
             */
            verification_status: "unverified" | "verified" | "conflict";
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
            /**
             * Legal Edition
             * @default
             */
            legal_edition: string;
            /** Research Checked At */
            research_checked_at?: string | null;
            /** Missing Evidence */
            missing_evidence?: string[];
            /**
             * Verification Notes
             * @default
             */
            verification_notes: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    official_announcements_api_official_announcements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementsView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    demo_login_api_auth_demo_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    max_login_api_auth_max_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessProfile-Output"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_profile_api_profile_put: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessProfile-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessProfile-Output"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"][];
                };
            };
        };
    };
    measure_detail_api_measures__measure_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measure_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_api_matches_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchesView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    plans_api_preparation_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"][];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_plan_api_preparation_plans_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_item_api_preparation_plans__plan_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path: {
                plan_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_versions_api_admin_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"][];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    new_measure_api_admin_measures_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMeasure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_version_api_admin_versions__version_id__clone_post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_api_admin_versions__version_id__put: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_api_admin_versions__version_id___action__post: {
        parameters: {
            query?: never;
            header: {
                /** @description Защита запросов приложения. Origin должен соответствовать PUBLIC_ORIGIN. */
                "X-App-Request": "1";
            };
            path: {
                version_id: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasureView"];
                };
            };
            /** @description Нет действующей сессии */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_api_max_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Недостаточно прав или запрос не прошёл проверку защиты */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
